### ISSUE TITLE
QuakeGVR framerate by default not in sync with refresh rate - vsync issue?

### ISSUE THREAD

**Issue by TrackBallPower** [DrBeef/QuakeGVR#14]
I noticed just how much smoother and much more immersive the QuakeGVR gameplay is after i installed the Lord Havoc's DPMod mod.
When i move forward in vanilla QuakeGVR and look on the floor, i notice continues micro-stutters.
When the Lord Havoc's DPMod mod is loaded and i look on the floor while moving, there are zero stutters, it is silky smooth and gives me the feeling that i can touch the walls.
The fact that Lord Havoc's DPMod gives a much smoother experience has been confirmed by both the  author as well as VR_Bummser in this reddit post:

https://www.reddit.com/r/quakegearvr/comments/9k5qsy/qgvr_running_smoother_on_dpmod/

If i am not mistaken, VR_Bummser uses a Samsung Galaxy S7. I use a Samsung Galaxy Note 9.

Could it be that vsync is not enabled by default in QuakeGVR?

**Comment by neitey** [comment]
Can second TrackBallPower's experience with Dpmod. Much smoother by default.

**Comment by DrBeef** [comment]
This isn't anything to do with vsync, and there's nothing I can really change myself.

For a start dpmod has much improved QuakeC code (not part of the engine, but part of the mod / assets themselves) over the vanilla quake install assets. This isn't something I can change in the engine. Recommendation to anyone is to play with dpmod enabled, it is much improved all round.

I can't really implement that code into my port, because it isn't part of the port, it is part of the assets.. If you want to see what I mean if you look at the contents of the dpmod, there's a folder in there called "qc" and in there, there's lots of QuakeC "qc" files that implement all the magic that the dpmod does.

I'm going to close this as I don't believe there's anything more to do than recommending people play with dpmod for an improved experience.

**Comment by TrackBallPower** [comment]
Would it then be an idea to (partly) integrate the Dpmod into QuakeGVR?
