### ISSUE TITLE
Request - option to center the weapon as in vanilla quake

### ISSUE THREAD

**Issue by neitey** [DrBeef/QuakeGVR#19]
Request - when playing QGVR with gamepad together with other mods the weapon is sometimes not visible anymore, probably because the mod (like Dpmod) and QGVR both change the position of the weapon to the rightside. It seems to add together. As a result in some mods the weapon isn't visable anymore or barely visible on the far right side.

So when playing with gamepad, there is no need for the weapon to be placed in the right side.
Request - option to center the weapon as in vanilla quake when using non 3DOF Gamepad

**Comment by TrackBallPower** [comment]
I can confirm that the weapons are barely visible in the Dpmod. 
Since the Dpmod is the only way to solve the continues micro stutters, this issue is now even more relevant.

**Comment by motorsep** [comment]
There is a cvar to set weapons centered (in DP_MOD) although I forgot what it is. Also it's mod's changes (QuakeC), not engine changes. 

Another thought comes to mind is that in VR centered weapons look really out of place.

**Comment by neitey** [comment]
Clarification - When playing the Sideload version (1.02?) the weapons are still visible in DPMOD in the right corner as intended by the mod. But when Dpmod is started with the newest github version of Qgvr the weapons are so far right that it's hard to tell which weapons is selected.

Since version 1.03 has the weapons set to the right side by default, i guess their must be two Cvars that reinforce each other. Resulting in a far out to the right weapons model.

For this case it would be nice to be able to recenter the weapon before starting the dpmod.

**Comment by DrBeef** [comment]
The latest version of QGVR offsets the weapons to the user's dominant hand (set in the Oculus remote configuration in the Oculus App). I mistakenly didn't wrap that offset with a cvar. It sounds like dpmod offsets it in a similar way (expect it is always to the right though, I doubt it uses "handedness", but is probably controlled by a cvar).

I can add a cvar so that the default weapon offset by the engine is set to 0, that way when dpmod applies its own offset the weapon is in the expected place. I had a quick look, couldn't find the offset cvar in dpmod, shouldn't be hard to wrap my change in a cvar (I am not going to add it to the options menu, that is a big faff for small use-case), but I now have limited amount of time, so might be a few days before I change this.

**Comment by DrBeef** [comment]
Please see latest release, the cvar to remove the weapon offset for use with dpmod is now available.

**Comment by TrackBallPower** [comment]
I just tried it, it works, the weapons are clearly visible now. Thanks!

**Comment by neitey** [comment]
I had issues, gonna try again.

Am So., 11. Nov. 2018 um 22:18 Uhr schrieb TrackBallPower <
notifications@github.com>:
